### ISSUE TITLE
Its needed to use http:// ?

### ISSUE THREAD

**Issue by P1nk13P1** [Dhole/Tumblr-rip#2]
Hello, I am very interested in your program and I am very surprised from Your awesome program, but its essential to use "http://" in the URL? because its not easy to write it on my PC, but thanks more,
PS: Can be added GUI for this awesome Downloader? Very thanks!

**Comment by Dhole** [comment]
I find it natural to require the "http://" in the URL.  I suggest you modify the code to your liking if you prefer not to write that part.  Just replace line 80 by `url = "http://" + sys.argv[1]`.
I have no plans on adding a GUI, but feel free to fork the code and add one if you want.
I'm closing this issue.
